import Foundation
import SourceModel
import WorkspaceCore
import XCTest
@testable import LanguageClient

final class SourceKitLSPDiscoveryTests: XCTestCase {
    func testDiscoversAnAbsoluteExecutableThroughXcrun() throws {
        let url = try SourceKitLSPDiscovery.discoverExecutableURL()
        XCTAssertTrue(url.path.hasPrefix("/"), "Discovery must resolve to an absolute path, got \(url.path)")
        XCTAssertTrue(FileManager.default.isExecutableFile(atPath: url.path))
        XCTAssertEqual(url.lastPathComponent, "sourcekit-lsp")
    }

    func testUsesXcrunAtItsFixedAbsoluteLocationNotAPathLookup() {
        // `xcrunURL` must be the fixed, well-known absolute path — never a
        // bare command name resolved via `PATH` or a shell (SPEC 13.2).
        XCTAssertEqual(SourceKitLSPDiscovery.xcrunURL.path, "/usr/bin/xcrun")
    }

    func testRejectsAMissingXcrun() {
        let bogus = URL(fileURLWithPath: "/nonexistent/xcrun-does-not-exist")
        XCTAssertThrowsError(try SourceKitLSPDiscovery.discoverExecutableURL(xcrunURL: bogus)) { error in
            XCTAssertEqual(error as? SourceKitLSPDiscoveryError, .xcrunNotFound)
        }
    }
}

/// Real, headless `sourcekit-lsp` integration tests against a small,
/// checked-in fixture Swift package (`Fixtures/SourceKitLSPFixture`).
/// These launch the actual toolchain binary discovered by
/// `SourceKitLSPDiscovery` — never the `FakeLanguageServer` fixture — and
/// exercise the full stack through `SwiftWorkspaceLanguageService`. A
/// normalized transcript of one such recorded session is checked in at
/// `Fixtures/sourcekit-lsp-transcript.normalized.json` (regenerated by
/// `Fixtures/probe_sourcekit.py`-style tooling) as a human-readable
/// reference for what real SourceKit-LSP returns for this exact fixture;
/// these tests assert against live behavior rather than diffing against
/// it byte-for-byte, since exact wording/log noise from a real toolchain
/// is not itself a stable contract.
///
/// No `XCUIApplication`/app UI is ever launched here — only the
/// `sourcekit-lsp` command-line process via `Process`, headlessly.
final class SourceKitLSPIntegrationTests: XCTestCase {
    private func fixtureRoot() throws -> URL {
        var directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        directory.appendPathComponent("Fixtures/SourceKitLSPFixture")
        guard FileManager.default.fileExists(atPath: directory.appendingPathComponent("Package.swift").path) else {
            throw XCTSkip("SourceKitLSPFixture package not found at \(directory.path)")
        }
        return directory
    }

    @MainActor
    private func makeTrustedService(root: URL) throws -> SwiftWorkspaceLanguageService {
        let identity = try WorkspaceIdentity(root: root)
        let suiteName = "SourceKitLSPIntegrationTests.\(UUID().uuidString)"
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suiteName))
        addTeardownBlock {
            UserDefaults(suiteName: suiteName)?.removePersistentDomain(forName: suiteName)
        }
        let store = WorkspaceTrustStore(defaults: defaults)
        store.trust(identity)

        let dependencies = SwiftWorkspaceLanguageService.Dependencies(
            connectionFactory: { configuration, onStateChange, onNotification in
                var configuration = configuration
                // Real SourceKit-LSP performs a background `swift build`
                // + indexing pass before results are meaningful; give it
                // generous headroom well beyond the fixture's fake-server
                // defaults.
                configuration.requestTimeout = 30
                return LanguageServerConnection(
                    configuration: configuration,
                    onStateChange: onStateChange,
                    onNotification: onNotification
                )
            }
        )
        return SwiftWorkspaceLanguageService(identity: identity, trustStore: store, dependencies: dependencies)
    }

    @MainActor
    func testInitializeHoverDefinitionReferencesSymbolsDiagnosticsSemanticTokensAgainstRealSourceKitLSP() async throws {
        let root = try fixtureRoot()
        let fileURL = root.appendingPathComponent("Sources/SourceKitLSPFixture/Greeter.swift")
        let service = try makeTrustedService(root: root)

        try await service.start()
        addTeardownBlock { await service.stop() }

        // --- Encoding negotiation (SPEC 6.3) ---
        // Recorded, documented finding for this toolchain (Xcode 26.5,
        // sourcekit-lsp from XcodeDefault.xctoolchain): it does not
        // declare `positionEncoding` in `InitializeResult.capabilities`
        // at all, so per the LSP 3.17 default Kod must — and does —
        // fall back to UTF-16 code-unit positions rather than the UTF-8
        // Kod prefers and advertised support for.
        let maybeCapabilities = await service.capabilities()
        let capabilities = try XCTUnwrap(maybeCapabilities)

        let snapshot = try SourceSnapshotLoader().load(url: fileURL, version: 1)
        try await service.didOpen(snapshot)

        let text = snapshot.text
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let hoverLineIndex = try XCTUnwrap(lines.firstIndex { $0.contains("func greet") })
        let hoverLine = String(lines[hoverLineIndex])
        let hoverCharacter = try XCTUnwrap(hoverLine.range(of: "greet")).lowerBound
        let hoverColumn = hoverLine.distance(from: hoverLine.startIndex, to: hoverCharacter) + 2
        let hoverOffset = try snapshot.utf8Offset(
            for: SourcePosition(line: hoverLineIndex, character: hoverColumn),
            encoding: .utf16
        )

        let hover = try await service.hover(snapshot: snapshot, utf8Offset: hoverOffset)
        let hoverValue = try XCTUnwrap(hover?.contents.value)
        XCTAssertTrue(hoverValue.contains("greet"), "Expected hover to mention 'greet', got: \(hoverValue)")

        let definitions = try await service.definition(snapshot: snapshot, utf8Offset: hoverOffset)
        XCTAssertFalse(definitions.isEmpty, "Expected at least one real definition location")
        XCTAssertEqual(definitions.first?.url.standardizedFileURL, fileURL.standardizedFileURL)

        // `references` and `workspace/symbol` depend on SourceKit-LSP's
        // background index store, which is still being built for a
        // moment after `didOpen`/`initialize` (observed via its own
        // `window/logMessage` "Indexing ..." chatter) — unlike hover and
        // definition, which resolve from the file's own AST and return
        // immediately. Retrying briefly is the standard, documented way
        // real SourceKit-LSP clients handle this startup latency; it is
        // not a workaround for a Kod-side bug.
        let references = try await retryUntilNonEmpty {
            try await service.references(snapshot: snapshot, utf8Offset: hoverOffset, includeDeclaration: true)
        }
        XCTAssertFalse(references.isEmpty, "Expected at least one real reference location")

        let symbols = try await service.documentSymbols(snapshot: snapshot)
        XCTAssertTrue(symbols.contains { $0.name == "Greeter" }, "Expected a 'Greeter' document symbol, got: \(symbols.map(\.name))")

        let workspaceSymbols = try await retryUntilNonEmpty {
            try await service.workspaceSymbols(query: "Greeter")
        }
        XCTAssertTrue(workspaceSymbols.contains { $0.name == "Greeter" })

        // --- Diagnostics: publish vs. pull capability gating ---
        // Recorded, documented finding: this SourceKit-LSP does not
        // advertise `diagnosticProvider` (pull) even though push
        // (`textDocument/publishDiagnostics`) works. Pull must therefore
        // report the precise capability limitation rather than
        // pretending to succeed with an empty/fake result.
        if capabilities.diagnosticProvider == nil {
            do {
                _ = try await service.pullDiagnostics(snapshot: snapshot)
                XCTFail("Expected pull diagnostics to be capability-gated off for this SourceKit-LSP")
            } catch SwiftLanguageServiceError.capabilityUnavailable {
                // Exact, expected limitation for this toolchain.
            }
        } else {
            _ = try await service.pullDiagnostics(snapshot: snapshot)
        }

        // --- Semantic tokens (full) ---
        let tokens = try await service.semanticTokens(snapshot: snapshot)
        XCTAssertFalse(tokens.isEmpty, "Expected real SourceKit-LSP semantic tokens for a non-trivial file")
        for token in tokens {
            XCTAssertTrue(token.utf8Range.lowerBound >= 0 && token.utf8Range.upperBound <= snapshot.utf8Count)
        }

        try await service.didClose(url: fileURL)
    }

    @MainActor
    func testMutatingRequestsAreNeverSentAndDynamicRegistrationWouldBeRejectedIfAttempted() async throws {
        // Real SourceKit-LSP is well-behaved and will not itself attempt
        // `client/registerCapability`/`workspace/applyEdit` against a
        // client that (like Kod) never advertised support for dynamic
        // registration or `workspace.applyEdit`. This test documents and
        // asserts that Kod's advertised capabilities during a real
        // handshake indeed omit them — the adversarial-server path
        // (a misbehaving server attempting these anyway) is covered by
        // `LanguageServerConnectionFixtureTests` using the deterministic
        // `FakeLanguageServer` "mutation-attempt" scenario, since a
        // well-behaved real server gives no opportunity to observe
        // rejection in the first place.
        let root = try fixtureRoot()
        let service = try makeTrustedService(root: root)
        try await service.start()
        addTeardownBlock { await service.stop() }

        let maybeCapabilities = await service.capabilities()
        let capabilities = try XCTUnwrap(maybeCapabilities)
        // Kod's own client capabilities never request rename/formatting/
        // codeAction/executeCommand — verified statically in
        // `MutationGuardTests`. Here we additionally confirm the server
        // handshake completed successfully without Kod needing to accept
        // any mutating request from it.
        XCTAssertNotNil(capabilities.hoverProvider)
    }
}

/// Retries `operation` a few times with a short delay, used only for the
/// two real-SourceKit-LSP requests (`references`, `workspace/symbol`)
/// that depend on background indexing rather than per-file AST info.
@MainActor
private func retryUntilNonEmpty<Element>(
    attempts: Int = 15,
    delayNanoseconds: UInt64 = 300_000_000,
    _ operation: () async throws -> [Element]
) async throws -> [Element] {
    var lastResult: [Element] = []
    for _ in 0..<attempts {
        lastResult = try await operation()
        if !lastResult.isEmpty {
            return lastResult
        }
        try await Task.sleep(nanoseconds: delayNanoseconds)
    }
    return lastResult
}
