import CryptoKit
import Foundation

/// One Ed25519 public key Kod trusts to sign the update feed, pinned in
/// app sources — never the private key, which never ships in the app.
/// Multiple keys may be valid at once so a rotation has an overlap
/// window, exactly like `ManagedLanguageServers.TrustedSigningKey`.
public struct TrustedUpdateSigningKey: Sendable, Equatable {
    public let id: String
    public let publicKeyBase64: String
    public let validFrom: Date
    public let validUntil: Date?

    public init(id: String, publicKeyBase64: String, validFrom: Date, validUntil: Date? = nil) {
        self.id = id
        self.publicKeyBase64 = publicKeyBase64
        self.validFrom = validFrom
        self.validUntil = validUntil
    }

    func isValid(at date: Date) -> Bool {
        guard date >= validFrom else {
            return false
        }
        if let validUntil {
            return date < validUntil
        }
        return true
    }

    func publicKey() throws -> Curve25519.Signing.PublicKey {
        guard let data = Data(base64Encoded: publicKeyBase64) else {
            throw UpdateFeedVerificationError.malformedTrustRoot(keyID: id)
        }
        return try Curve25519.Signing.PublicKey(rawRepresentation: data)
    }
}

/// The full set of keys Kod's shipped build trusts for the update feed,
/// plus explicit revocation of specific versions discovered to be
/// broken or compromised after publication (independent of whatever the
/// feed itself still lists).
///
/// Production key material is never generated by or stored in this
/// repository: see `Scripts/release/README.md` for the release-key
/// handling process. `UpdateFeedTrustRoot.production` below is
/// intentionally empty until that offline process publishes a real
/// public key; `UpdateFeedTrustRoot.fixture` (test-only, in
/// `UpdaterCoreTests`) uses a fixed, clearly-labeled non-secret key pair
/// that signs nothing but this repository's own fixtures.
public struct UpdateFeedTrustRoot: Sendable, Equatable {
    public let pinned: [TrustedUpdateSigningKey]
    public let revokedVersions: Set<String>

    public init(pinned: [TrustedUpdateSigningKey], revokedVersions: Set<String> = []) {
        self.pinned = pinned
        self.revokedVersions = revokedVersions
    }

    /// No notarized, production Kod-release Ed25519 update-signing key
    /// currently exists in this environment. An empty trust root makes
    /// `UpdateFeedVerifier` reject every feed outright with
    /// `.noTrustedKeyConfigured` — never a fallback that treats "no key
    /// configured" as "trust anything" (SPEC 13.2: process security;
    /// this is the update-feed analog of that same non-negotiable
    /// choke point).
    public static let production = UpdateFeedTrustRoot(pinned: [])

    func key(id: String, generatedAt: Date) -> TrustedUpdateSigningKey? {
        pinned.first { $0.id == id && $0.isValid(at: generatedAt) }
    }
}

public enum UpdateFeedVerificationError: Error, Equatable, Sendable {
    case noTrustedKeyConfigured
    case unknownSigningKeyID(String)
    case signatureInvalid
    case malformedTrustRoot(keyID: String)
    case malformedFeedDocument
    case feedFormatVersionUnsupported(Int)
    case downloadedArtifactDigestMismatch(expectedSha256Hex: String, actualSha256Hex: String)
}
