import CryptoKit
import Foundation

/// One Ed25519 public key Kod trusts to sign catalogs, pinned in app
/// sources (SPEC 6.5/13: "Sign catalog canonical bytes with a pinned
/// CryptoKit Curve25519/Ed25519 trust root" — never the private key,
/// which never ships in the app). Multiple keys may be valid at once so
/// a rotation has an overlap window: the release process starts signing
/// with a new key before the old key's `validUntil` and before it is
/// ever removed from `CatalogTrustRoot.pinned`.
public struct TrustedSigningKey: Sendable, Equatable {
    /// Stable identifier embedded in `SignedCatalogDocument.signingKeyID`
    /// so verification can pick the one pinned key that produced a given
    /// signature without trial-and-error across every pinned key.
    public let id: String

    /// Raw 32-byte Ed25519 public key, base64-encoded.
    public let publicKeyBase64: String

    /// The key is only accepted for catalogs whose `generatedAt` falls
    /// in `[validFrom, validUntil)` (or `validUntil == nil` for "still
    /// current"). This is what makes rotation explicit: an old key stops
    /// verifying *new* catalogs at a known instant, while catalogs
    /// signed and distributed while it was current keep verifying with
    /// it forever (so a key already fully retired can still be pinned
    /// read-only for historical verification if ever needed, without
    /// being usable to forge a *new* catalog).
    public let validFrom: Date
    public let validUntil: Date?

    public init(id: String, publicKeyBase64: String, validFrom: Date, validUntil: Date? = nil) {
        self.id = id
        self.publicKeyBase64 = publicKeyBase64
        self.validFrom = validFrom
        self.validUntil = validUntil
    }

    func isValid(at date: Date) -> Bool {
        guard date >= validFrom else {
            return false
        }
        if let validUntil {
            return date < validUntil
        }
        return true
    }

    func publicKey() throws -> Curve25519.Signing.PublicKey {
        guard let data = Data(base64Encoded: publicKeyBase64) else {
            throw CatalogVerificationError.malformedTrustRoot(keyID: id)
        }
        return try Curve25519.Signing.PublicKey(rawRepresentation: data)
    }
}

/// The full set of keys Kod's shipped build trusts, plus explicit
/// revocation of specific catalog format versions or artifact digests
/// discovered to be compromised after publication (independent of, and
/// finer-grained than, per-entry `revoked`/`revocationReason`, which is
/// under the *catalog author's* control; `revokedArtifactDigests` is
/// under *this app build's* control, for a digest Kod itself must never
/// install again even if a stale, still-validly-signed catalog still
/// lists it).
///
/// Production key material is never generated by or stored in this
/// repository: see `Scripts/managed-install-signing/README.md` for the
/// release-key handling process. `CatalogTrustRoot.production` below is
/// intentionally empty until that offline process publishes a real
/// public key; `CatalogTrustRoot.fixture` (test-only, in
/// `ManagedLanguageServersTests`) uses a fixed, clearly-labeled
/// non-secret key pair that signs nothing but this repository's own
/// fixtures.
public struct CatalogTrustRoot: Sendable, Equatable {
    public let pinned: [TrustedSigningKey]
    public let revokedArtifactDigestsHex: Set<String>

    public init(pinned: [TrustedSigningKey], revokedArtifactDigestsHex: Set<String> = []) {
        self.pinned = pinned
        self.revokedArtifactDigestsHex = revokedArtifactDigestsHex
    }

    /// The trust root Kod's shipped app build uses. Empty: no
    /// notarized, production Kod-release Ed25519 key currently exists
    /// in this environment (see `Scripts/managed-install-signing/README.md`'s
    /// "release provisioning gap" section). An empty trust root makes
    /// `CatalogVerifier` reject every catalog outright with
    /// `CatalogVerificationError.noTrustedKeyConfigured`, which is the
    /// correct, honest behavior — never a fallback that treats "no key
    /// configured" as "trust anything."
    public static let production = CatalogTrustRoot(pinned: [])

    func key(id: String, generatedAt: Date) -> TrustedSigningKey? {
        pinned.first { $0.id == id && $0.isValid(at: generatedAt) }
    }
}

public enum CatalogVerificationError: Error, Equatable, Sendable {
    case noTrustedKeyConfigured
    case unknownSigningKeyID(String)
    case signatureInvalid
    case malformedTrustRoot(keyID: String)
    case malformedCatalogDocument
    case catalogFormatVersionUnsupported(Int)
    case entryBelowMinimumKodVersion(serverID: String, requires: SemanticVersion, running: SemanticVersion)
    case duplicateArtifactArchitecture(serverID: String, architecture: ManagedInstallArchitecture)
}
