import Foundation

/// A deterministic, seeded pseudo-random source shared by every fuzz/
/// property test suite in this repository (renderer/range math,
/// Unicode/encoding positions, LSP framing, themes/catalogs/archives,
/// Git parsers, Markdown/SVG/image/JSON/plist parsers, persistence
/// migrations, support-bundle redaction, and hostile process output —
/// SPEC 16.1: "Property and fuzz tests for Unicode positions, malformed
/// LSP frames, hostile theme JSON, archive extraction, diff parsing,
/// and renderer range math").
///
/// Using SplitMix64 (a small, well-known, non-cryptographic generator)
/// rather than `SystemRandomNumberGenerator` means:
///   - Every run with the same seed produces byte-for-byte identical
///     inputs, so a failure is always reproducible from the seed alone.
///   - `FuzzFailureReporter` below can print that exact seed on any
///     failure, so a human can rerun `FuzzRandomSource(seed: <printed
///     seed>)` to reproduce it deterministically without needing to
///     capture or replay the actual generated bytes.
public struct FuzzRandomSource: RandomNumberGenerator {
    public let seed: UInt64
    private var state: UInt64

    public init(seed: UInt64) {
        self.seed = seed
        self.state = seed
    }

    public mutating func next() -> UInt64 {
        state = state &+ 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }
}

/// One fuzz/property test suite's bounded run: a fixed iteration count
/// (never "run until a timeout," so CI duration stays predictable) and
/// a base seed derived from the suite name so different suites explore
/// different input spaces even when run the same day, while a single
/// suite's own run is 100% reproducible across machines and Swift
/// versions (SplitMix64's arithmetic is portable, unlike hashValue-based
/// seeding).
public enum FuzzRun {
    /// The default bounded iteration count for a fuzz/property test
    /// method — enough to exercise a meaningfully wide input space
    /// while keeping every suite's total runtime well under a second
    /// per method on the reference machine.
    public static let defaultIterationCount = 500

    /// Derives a stable, human-typeable base seed from a fixed label
    /// (typically the test method name), so reordering test methods
    /// never changes what inputs a given test explores, and a failure's
    /// printed seed is always exactly reproducible by passing the same
    /// label back in.
    public static func baseSeed(for label: StaticString) -> UInt64 {
        var hasher = FNV1aHasher()
        hasher.combine(label)
        return hasher.finalize()
    }

    /// Runs `body` `iterationCount` times, handing it a fresh
    /// `FuzzRandomSource` seeded deterministically from `label` and the
    /// iteration index. On any thrown error, wraps it with the exact
    /// seed that produced it so the failure message alone is enough to
    /// reproduce the run via `FuzzRandomSource(seed:)`.
    public static func run(
        _ label: StaticString,
        iterations: Int = defaultIterationCount,
        _ body: (inout FuzzRandomSource) throws -> Void
    ) throws {
        let base = baseSeed(for: label)
        for iteration in 0..<iterations {
            let seed = base &+ UInt64(iteration)
            var source = FuzzRandomSource(seed: seed)
            do {
                try body(&source)
            } catch {
                throw FuzzFailure(label: "\(label)", seed: seed, iteration: iteration, underlying: error)
            }
        }
    }
}

/// A tiny, dependency-free FNV-1a hash used only to turn a fixed label
/// into a stable 64-bit base seed — not for anything security-sensitive.
private struct FNV1aHasher {
    private var hash: UInt64 = 0xCBF2_9CE4_8422_2325

    mutating func combine(_ value: StaticString) {
        value.withUTF8Buffer { buffer in
            for byte in buffer {
                hash ^= UInt64(byte)
                hash = hash &* 0x0000_0100_0000_01B3
            }
        }
    }

    func finalize() -> UInt64 { hash }
}

/// Wraps any fuzz-iteration failure with the exact seed and iteration
/// index that produced it, so a CI failure message alone tells a human
/// exactly how to reproduce it locally — never just "a fuzz test
/// failed somewhere in 500 iterations."
public struct FuzzFailure: Error, CustomStringConvertible {
    public let label: String
    public let seed: UInt64
    public let iteration: Int
    public let underlying: Error

    public var description: String {
        "Fuzz failure in \"\(label)\" at iteration \(iteration) (seed: \(seed)): \(underlying). " +
            "Reproduce with FuzzRandomSource(seed: \(seed))."
    }
}

/// Generates bounded-size random inputs for common fuzz-target shapes.
/// Every generator takes an explicit maximum size so a single
/// misconfigured call site can never cause unbounded allocation —
/// matching SPEC 12.3's "no supported or adversarial input may cause
/// unbounded allocation" for the fixtures these tests feed into
/// production code, not just for production code itself.
public enum FuzzGenerators {
    public static func randomByte(_ source: inout FuzzRandomSource) -> UInt8 {
        UInt8.random(in: 0...255, using: &source)
    }

    public static func randomBytes(count: Int, _ source: inout FuzzRandomSource) -> [UInt8] {
        (0..<max(0, count)).map { _ in randomByte(&source) }
    }

    /// Random bytes of a random length in `range`, bounded above so a
    /// fuzz loop can never balloon memory even with an adversarial
    /// `range` argument.
    public static func randomBytes(lengthIn range: ClosedRange<Int>, _ source: inout FuzzRandomSource) -> [UInt8] {
        let boundedUpper = min(range.upperBound, 1 << 20)
        let length = Int.random(in: range.lowerBound...max(range.lowerBound, boundedUpper), using: &source)
        return randomBytes(count: length, &source)
    }

    /// A random Unicode scalar drawn from a mix of ASCII, Latin-1
    /// supplement, combining marks, emoji, and other astral-plane
    /// scalars — deliberately including grapheme-cluster-breaking and
    /// multi-UTF-16-unit code points, since those are exactly what have
    /// historically broken byte/UTF-8/UTF-16 offset math.
    public static func randomScalar(_ source: inout FuzzRandomSource) -> Unicode.Scalar {
        let ranges: [ClosedRange<UInt32>] = [
            0x20...0x7E, // printable ASCII
            0xA0...0xFF, // Latin-1 supplement
            0x300...0x36F, // combining diacritical marks
            0x1F300...0x1F5FF, // misc symbols and pictographs (emoji, multi-UTF-16-unit)
            0x4E00...0x4FFF // a slice of CJK unified ideographs
        ]
        let chosenRange = ranges[Int.random(in: 0..<ranges.count, using: &source)]
        let value = UInt32.random(in: chosenRange, using: &source)
        return Unicode.Scalar(value) ?? Unicode.Scalar(0x20)
    }

    /// A random `String` of `scalarCount` scalars from
    /// `randomScalar(_:)`, useful for Unicode/encoding-position fuzzing
    /// where the exact grapheme/UTF-16 structure must stay
    /// unconstrained rather than always-well-formed ASCII.
    public static func randomUnicodeString(scalarCount: Int, _ source: inout FuzzRandomSource) -> String {
        var scalars = String.UnicodeScalarView()
        for _ in 0..<max(0, scalarCount) {
            scalars.append(randomScalar(&source))
        }
        return String(scalars)
    }
}
